server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
---
sidecar: 
  port: 8000
  health-uri: http://10.170.8.152:${sidecar.port}/health
  home-page-uri: http://10.170.8.152:${sidecar.port}/
    
#---
#sidecar: 
#  port: 8001
#  health-uri: http://localhost:${sidecar.port}/health
#  home-page-uri: http://localhost:${sidecar.port}/